<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="KAPPO-NOTE" name="runner.TestRunner" tests="3" failures="1" timestamp="2021-02-16T10:59:03 BRT" time="2.984" errors="1">
  <testcase name="runScenario" time="0.192" classname="runner.TestRunner">
    <failure type="java.lang.AssertionError" message="expected:&lt;200&gt; but was:&lt;404&gt;">
      <![CDATA[java.lang.AssertionError: expected:<200> but was:<404>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:633)
at steps.StepDefinitions.validarStatusCode(StepDefinitions.java:155)
at ✽.Eu devo verificar que o HTTP StatusCode retornado é 200(file:///home/mkapobianco/Projects/TestesAutomatizadosBrasilPrev/src/test/java/features/BuscarClientes.feature:14)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase name="runScenario" time="0.432" classname="runner.TestRunner"/>
  <system-out/>
  <testcase name="runScenario" time="2.360" classname="runner.TestRunner">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at steps.StepDefinitions.validarCadastroDeNovoCliente(StepDefinitions.java:160)
at ✽.Eu devo ver que o corpo de resposta retornado esta dentro do especificado(file:///home/mkapobianco/Projects/TestesAutomatizadosBrasilPrev/src/test/java/features/BuscarClientes.feature:8)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- runner.TestRunner -->
